models/Dialog.php
<?php

namespace app\modules\communication\models;

use Yii;
use yii\helpers\Url;
use yii\db\IntegrityException;
use app\behaviors\DateTimeBehavior;
use app\modules\user\models\User;

/**
 * This is the model class for table "comm_dialog".
 *
 * @property integer      $id
 * @property string       $type
 * @property string       $created_at
 *
 * @property string       $viewUrl
 *
 * @property User[]       $users
 * @property DialogLink[] $links
 * @property Message[]    $messages
 * @property Message      $lastMessage
 */
class Dialog extends \yii\db\ActiveRecord
{

    const TYPE_DIALOG = '1';
    const TYPE_ROOM = '2';

    /**
     * @var integer
     */
    protected $last_message_id;

    /**
     * @var integer
     */
    public $new_message_count = 0;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'comm_dialog';
    }

    /**
     * @inheritdoc
     */
    public static function find()
    {
        return new class(get_called_class()) extends \yii\db\ActiveQuery
        {

            /**
             * @return $this
             */
            public function active()
            {
                return $this->innerJoin('comm_dialog_link', [
                    'and',
                    '`comm_dialog_link`.`dialog_id` = `comm_dialog`.`id`',
                    '`comm_dialog_link`.`user_id` = :uid',
                    ['comm_dialog_link.active' => true],
                ]);
            }

            /**
             * @return $this
             */
            public function sortByLastMessage($whitStatus = false)
            {
                $this->active();

                if ($this->select === null) {
                    $this->select('comm_dialog.*');
                }
                $this->addSelect(['last_message_id' => 'MAX(`comm_dialog_message`.`id`)']);
                $this->leftJoin('comm_dialog_message', [
                    'and',
                    '`comm_dialog_message`.`dialog_id` = `comm_dialog`.`id`',
                    '`comm_dialog_message`.`created_at` >= `comm_dialog_link`.`joined_at`',
                    '`comm_dialog_message`.`id` NOT IN (SELECT `message_id` FROM `comm_dialog_message_hidden` WHERE `user_id` = :uid)',
                ]);

                if ($whitStatus) {
                    $this->leftJoin('comm_dialog_message_new', '`comm_dialog_message_new`.`message_id` = `comm_dialog_message`.`id` AND `comm_dialog_message_new`.`user_id` = :uid');
                    $this->addSelect(['new_message_count' => 'SUM(IF(`comm_dialog_message_new`.`message_id` IS NULL, 0, 1))']);
                }
                $this->orderBy(['last_message_id' => SORT_DESC]);

                return $this;
            }
        };
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'datetime' => [
                'class'      => DateTimeBehavior::className(),
                'type'       => DateTimeBehavior::TYPE_DATETIME,
                'attributes' => [
                    self::EVENT_BEFORE_INSERT => ['created_at'],
                ],
            ]
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLinks()
    {
        return $this->hasMany(DialogLink::className(), ['dialog_id' => 'id'])->inverseOf('dialog');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers($callback = null)
    {
        return $this->hasMany(User::className(), ['id' => 'user_id'])->via('links', $callback);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMessages()
    {
        return $this->hasMany(Message::className(), ['dialog_id' => 'id'])->inverseOf('dialog');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLastMessage()
    {
        return $this->hasOne(Message::className(), ['dialog_id' => 'id', 'id' => 'last_message_id'])->inverseOf('dialog');
    }

    /**
     * @return string
     */
    public function getViewUrl()
    {
        return Url::to(['/communication/dialog/view', 'id' => $this->id]);
    }

    /**
     * @return \self
     */
    public static function create($type = self::TYPE_DIALOG)
    {
        $model       = new self;
        $model->type = $type;
        $model->save();

        return $model;
    }

    /**
     * создать диалог для двух пользователей, если его еще нет
     *
     * @param array  $ids  - идентификаторы пользователей
     * @param string $type - тип диалога
     *
     * @throws \Exception
     *
     * @return Dialog
     */
    public static function createForUsers($ids, $type = self::TYPE_DIALOG)
    {
        if (count($ids) != 2) {
            throw new \Exception('Для создания диалога необходимо два пользователя!');
        }

        if ($dialog = self::findDialogByUserIds($ids)) {
            return $dialog;
        }

        $dialog       = new self;
        $dialog->type = $type;
        $dialog->save();

        foreach ($ids as $id) {
            $dialog->addUser($id);
        }

        return $dialog;
    }

    /**
     * найти диалог по идентифкаторам пользователей
     *
     * @param $ids - идентификаторы пользователей, входящих в диалог
     *
     * @return Dialog|null
     */
    private static function findDialogByUserIds($ids)
    {
        $query = Dialog::find()->where(['type' => Dialog::TYPE_DIALOG]);
        $query->innerJoin(['l' => DialogLink::tableName()], [
            'and',
            '`l`.`dialog_id` = `comm_dialog`.`id`',
            ['l.user_id' => current($ids)],
            ['l.active' => true],
        ]);
        $query->innerJoin(['r' => DialogLink::tableName()], [
            'and',
            '`r`.`dialog_id` = `l`.`dialog_id`',
            ['r.user_id' => next($ids)],
            ['r.active' => true],
        ]);

        return $query->one();
    }

    public function addUser($users = null, $dt = null)
    {
        if ($users === null)
            $users = Yii::$app->user->id;

        if (!is_array($users))
            $users = (array)$users;

        if ($dt === null)
            $dt = date('Y-m-d H:i:s');

        $rows = array_map(function ($value) use ($dt) {
            return [$this->id, $value, true, $dt];
        }, $users);

        try {
            $this->getDb()->createCommand()->batchInsert(DialogLink::tableName(), ['dialog_id', 'user_id', 'active', 'joined_at'], $rows)->execute();
        } catch (IntegrityException $ex) {
            return false;
        }
    }

}

controllers/DialogController.php
<?php

namespace app\modules\communication\controllers;

use Yii;
use yii\helpers\Url;
use yii\web\NotFoundHttpException;
use yii\data\ActiveDataProvider;
use app\modules\communication\models\Sender;
use app\modules\communication\models\Dialog;
use app\modules\communication\models\Message;
use app\modules\communication\models\DialogLink;

class DialogController extends \app\components\AccountController
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors           = parent::behaviors();
        $behaviors['access'] = [
            'class' => 'yii\filters\AccessControl',
            'rules' => [
                [
                    'allow' => true,
                    'roles' => ['@'],
                ]
            ],
        ];
        $behaviors['verbs']  = [
            'class'   => 'yii\filters\VerbFilter',
            'actions' => [
                'send' => ['post'],
                'hide' => ['post'],
            ]
        ];

        return $behaviors;
    }

    /**
     * Запрос для списка диалогов
     * @return \yii\db\ActiveQuery
     */
    private function getDialogQuery()
    {
        $query = Dialog::find();
        $query->addParams(['uid' => Yii::$app->user->id]);
        $query->sortByLastMessage(true);
        $query->with([
            'users' => function ($query) {
                $query->except();
            },
            'users.profile.file',
            'lastMessage',
        ]);
        $query->groupBy(['comm_dialog.id']);

        return $query;
    }

    /**
     * Список диалогов пользователя
     */
    public function actionIndex($id = null)
    {
        $model        = new Sender;
        $dataProvider = new ActiveDataProvider([
            'query'      => $this->getDialogQuery(),
            'pagination' => [
                'pageSize' => 15,
            ]
        ]);

        return $this->render('index', ['dataProvider' => $dataProvider, 'model' => $model, 'dialogId' => $id]);
    }

    /**
     * Список последнийх диалогов для dropdown
     */
    public function actionLast()
    {
        $query = $this->getDialogQuery();
        $query->limit(8);

        return $this->renderPartial('partial/last', ['models' => $query->all()]);
    }

    /**
     * Перейти к диалогу. Перед этим найти последнее непрочитанное сообщение начать показ сообщений с него.
     *
     * @param integer $id
     */
    public function actionEnter($id)
    {
        /* @var $model Dialog */
        $query = Dialog::find();
        $query->addParams(['uid' => Yii::$app->user->id]);
        $query->with([
            'users' => function ($query) {
                $query->except();
            },
            'users.profile.file',
        ]);
        $query->active();
        $query->andWhere(['comm_dialog.id' => $id]);
        $model = $query->one();

        if ($model === null) {
            throw new NotFoundHttpException;
        }
        $message = $model->getMessages()->addParams(['uid' => Yii::$app->user->id])->onlyNew()->limit(1)->one();

        if ($message !== null) {
            $message->scroll = Message::SCROLL_INIT;
        } else {
            $message = new Message([
                'dialog_id' => $model->id,
                'scroll'    => Message::SCROLL_UP,
            ]);
        }
        $message->user_id = Yii::$app->user->id;
        $dataProvider     = $message->search();

        return $this->asJson([
            'success' => true,
            'data'    => [
                'url'    => Url::to(['view', 'id' => $id]),
                'scroll' => $message->scroll,
                'html'   => $this->renderPartial('partial/enter', [
                    'model'   => $model,
                    'sender'  => new Sender,
                    'content' => $this->renderPartial('partial/view', ['dataProvider' => $dataProvider])
                ]),
            ],
        ]);
    }

    /**
     * Просмотр сообщений в диалоге
     *
     * @param integer $id - ID диалога
     * @param integer $m
     * @param integer $s
     *
     * @throws NotFoundHttpException
     */
    public function actionView($id, $m = null, $s = Message::SCROLL_UP)
    {
        $model            = new Message;
        $model->id        = $m;
        $model->dialog_id = $id;
        $model->user_id   = Yii::$app->user->id;
        $model->scroll    = $s;

        $dataProvider = $model->search();

        return $this->asJson([
            'success' => true,
            'count'   => $dataProvider->totalCount,
            'data'    => [
                'html'   => $this->renderPartial('partial/view', ['dataProvider' => $dataProvider]),
                'scroll' => $s,
            ],
        ]);
    }

    /**
     * Отправить сообщение для диалога
     *
     * @param integer $id
     */
    public function actionSend($id)
    {
        $model         = new Sender;
        $model->from   = Yii::$app->user->id;
        $model->to     = $id;
        $model->target = Sender::TARGET_DIALOG;

        if ($model->load(Yii::$app->request->post()) && $model->send()) {
            return $this->asJson([
                'success' => true,
                'data'    => [
                    'url' => Url::to(['view', 'id' => $id]),
                ]
            ]);
        } elseif ($model->hasErrors()) {
            $attribute = array_keys($model->errors)[0];

            return $this->asJson(['success' => false, 'data' => ['message' => $model->getFirstError($attribute)]]);
        }
    }

    /**
     * связаться с технической поддрежкой
     */
    public function actionContactSupport()
    {
        // идентификатор техподдержки
        $supportId = YII_ENV_DEV ? 4 : 154;
        $dialog    = Dialog::createForUsers([Yii::$app->user->id, $supportId]);

        return $this->redirect('/communication/dialog/index?id=' . $dialog->id);
    }

    /**
     * Скрыть диалог от пользователя
     *
     * @param integer $id
     */
    public function actionHide($id)
    {
        DialogLink::updateAll(['active' => false], [
            'dialog_id' => $id,
            'user_id'   => Yii::$app->user->id,
            'active'    => true,
        ]);

        return $this->redirect(['index']);
    }

}

controllers/MessageController.php
<?php

namespace app\modules\communication\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use app\modules\communication\models\Message;
use app\modules\communication\models\Sender;

class MessageController extends \app\components\AccountController {

	/**
	 * @inheritdoc
	 */
	public function behaviors() {
		$behaviors = parent::behaviors();
		$behaviors['access'] = [
			'class' => 'yii\filters\AccessControl',
			'rules' => [
				[
					'allow' => true,
					'roles' => ['@'],
				]
			],
		];
		$behaviors['verbs'] = [
			'class' => 'yii\filters\VerbFilter',
			'actions' => [
				'send' => ['post'],
				'hide' => ['post'],
			]
		];
		return $behaviors;
	}

	/**
	 * Поиск по сообщениям
	 * @param string $q - Запрос
	 * @param integer $dialog_id - ID диалога, если надо сузить поиск до одного диалога
	 */
	public function actionSearch($q, $dialog_id = null) {
		$query = Message::find();
		$query->addParams(['uid' => Yii::$app->user->id]);

		if (!empty($dialog_id)) {
			$query->fromDialog($dialog_id);
		} else {
			$query->fromActiveDialogs()->notHidden();
		}
		$query->orderBy(['comm_dialog_message.created_at' => SORT_DESC]);

		if (empty($q))
			$query->andWhere('0=1');

		if (!empty($dialog_id))
			$query->andWhere(['comm_dialog_message.dialog_id' => $dialog_id]);

		$query->andWhere(['like', 'text', $q]);
		$dataProvider = new ActiveDataProvider(['query' => $query, 'pagination' => ['pageSize' => 10]]);
		return $this->render('search', ['dataProvider' => $dataProvider]);
	}

	/**
	 * Отправить сообщение пользователю. При надобности будет создан новый диалог.
	 */
	public function actionSend($id) {
		Yii::$app->response->format = 'json';

		$model = new Sender;
		$model->from = Yii::$app->user->id;
		$model->to = $id;
		$model->target = Sender::TARGET_USER;

		if ($model->load(Yii::$app->request->post()) && $model->send()) {
			return ['success' => true];
		} else {
			return ['success' => false, 'data' => ['messages' => array_values($model->errors)]];
		}
	}

	/**
	 * Скрыть сообщения
	 */
	public function actionHide() {
		Yii::$app->response->format = 'json';

		$query = Message::find();
		$query->addParams(['uid' => Yii::$app->user->id]);
		$query->select('comm_dialog_message.id');
		$query->andWhere(['comm_dialog_message.id' => Yii::$app->request->post('id')]);
		$query->fromActiveDialogs()->notHidden();
		$ids = $query->createCommand()->queryColumn();

		if (empty($ids))
			return ['success' => false];

		$rows = array_map(function ($id) {
			return [
				$id,
				Yii::$app->user->id,
			];
		}, $ids);
		Yii::$app->db->createCommand()->batchInsert('comm_dialog_message_hidden', ['message_id', 'user_id'], $rows)->execute();
		return ['success' => true];
	}

	/**
	 * Получить кол-во непрочтенных сообщений (в диалоге, если ID диалога указан)
	 * @param integer $dialog_id
	 */
	public function actionGetCount($dialog_id = null) {
		Yii::$app->response->format = 'json';

		$query = Message::find()->notHidden()->onlyNew()->fromActiveDialogs();
		$query->addParams(['uid' => Yii::$app->user->id]);

		if (!empty($dialog_id))
			$query->andWhere(['comm_dialog_message.dialog_id' => $dialog_id]);

		return ['count' => $query->count()];
	}

}

views/dialog/partial/enter.php
<?php
/* @var $this \yii\web\View */
/* @var $model \app\modules\communication\models\Dialog */
/* @var $sender \app\modules\communication\models\Sender */
/* @var $content string */

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\bootstrap\Dropdown;
?>
<div class="action-header bg palette-Grey-100">
	<div class="ah-label">
		<div class="menu-collapse visible-xs" data-ma-action="message-toggle">
			<div class="mc-wrap">
				<div class="mcw-line top bgm-gray"></div>
				<div class="mcw-line center bgm-gray"></div>
				<div class="mcw-line bottom bgm-gray"></div>
			</div>
		</div>
		<?= implode(', ', ArrayHelper::getColumn($model->users, 'profile.first_name')); ?>
	</div>

	<?= Html::beginForm(['message/search', 'dialog_id' => $model->id], 'GET', ['id' => 'comm-message-search-form', 'class' => 'ah-search']); ?>
	<input type="text" placeholder="<?php echo Yii::t('app/communication', 'views.dialog.partial.enter.text-1') ?>" class="ahs-input" name="q" autocomplete="off">
	<i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
	<?= Html::endForm(); ?>

	<ul class="actions">
		<li>
			<?=
			Html::a('<i class="zmdi zmdi-delete"></i>', ['message/hide'], [
				'id' => 'comm-message-hide',
				'title' => Yii::t('app/communication', 'views.dialog.partial.enter.text-2'),
				'data' => [
					'swal-confirm' => Yii::t('app/communication', 'views.dialog.partial.enter.text-3'),
					'swal-method' => 'false'
				],
				'style' => 'display: none',
			]);
			?>
		</li>
		<li>
			<a href="#" class="ah-search-trigger" data-ma-action="ah-search-open" title="<?php echo Yii::t('app/communication', 'views.dialog.partial.enter.text-4') ?>">
				<i class="zmdi zmdi-search"></i>
			</a>
		</li>
		<li class="dropdown">
			<a href="#" data-toggle="dropdown">
				<i class="zmdi zmdi-more-vert"></i>
			</a>
			<?=
			Dropdown::widget([
				'encodeLabels' => false,
				'options' => ['class' => 'dropdown-menu-right dm-icon'],
				'items' => [
					[
						'label' => '<i class="zmdi zmdi-close"></i> ' .Yii::t('app/communication', 'views.dialog.partial.enter.text-5'),
						'url' => ['hide', 'id' => $model->id],
						'linkOptions' => [
							'data' => [
								'swal-confirm' => Yii::t('app/communication', 'views.dialog.partial.enter.text-6'),
								'swal-method' => 'post'
							]
						]
					],
					[
						'label' => '<i class="zmdi zmdi-account-add"></i> ' . Yii::t('app/communication', 'views.dialog.partial.enter.text-7'),
						'url' => '#',
						'visible' => YII_ENV_DEV
					]
				]
			]);
			?>
		</li>
	</ul>
</div>
<div id="comm-message-list" class="list-group lg-alt" style="margin-bottom: 85px; min-height: 190px;">
	<a href="#" class="list-group-item text-center c-gray" id="comm-message-load-more">
		<i class="zmdi zmdi-long-arrow-up zmdi-hc-fw"></i> <?php echo Yii::t('app/communication', 'views.dialog.partial.enter.text-8') ?>
	</a>
	<?= $content; ?>
</div>
<?
echo Html::beginForm(['send', 'id' => $model->id], 'POST', [
	'id' => 'comm-message-form',
	'class' => 'ms-reply m-t-0',
]);
echo Html::activeTextarea($sender, 'text', ['maxlength' => true, 'placeholder' => Yii::t('app/communication', 'views.dialog.partial.enter.text-9')]);
echo Html::submitButton('<i class="zmdi zmdi-mail-send"></i>');
echo Html::endForm();

views/dialog/partial/index-item.php
<?php
/* @var $this \yii\web\View */
/* @var $model \app\modules\communication\models\Dialog */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use app\modules\user\widgets\UserImg;
?>
<a class="list-group-item media comm-dialog-list-item<?= $model->new_message_count > 0 ? ' has-new-messages' : ''; ?>" href="<?= Url::to(['enter', 'id' => $model->id]); ?>">
	<div class="pull-left">
		<? if (count($model->users) > 1): ?>
			<div class="avatar-char bg palette-Blue">
				<i class="zmdi zmdi-accounts-alt"></i>
			</div>
		<? else: ?>
			<?= UserImg::widget(['model' => $model->users[0]]); ?>
		<? endif; ?>
	</div>

	<? if ($model->new_message_count > 0): ?>
		<div class="pull-right">
			<span class="label label-primary m-t-15 d-ib"><?= $model->new_message_count; ?></span>
		</div>
	<? endif; ?>
	<div class="media-body">
		<div class="lgi-heading">
			<? if (count($model->users) > 1): ?>
				<?= implode(', ', ArrayHelper::getColumn($model->users, 'profile.first_name')); ?>
			<? else: ?>
				<?= $model->users[0]->profile->name; ?>
			<? endif; ?>
		</div>
		<small class="lgi-text">
			<? if ($model->lastMessage !== null): ?>
				<? if ($model->lastMessage->user_id == Yii::$app->user->id): ?>
					<b><?php echo Yii::t('app/communication', 'views.dialog.partial.last.text-1')?></b>
				<? elseif (count($model->users) > 1): ?>
					<b><?= $model->lastMessage->user->profile->first_name; ?>:</b>
				<? endif; ?>
				<?= $model->lastMessage->text; ?>
			<? else: ?>
				<i class="zmdi zmdi-alert-triangle"></i>
				<small><?php echo Yii::t('app/communication', 'views.dialog.partial.last.text-2')?></small>
			<? endif; ?>
		</small>
	</div>
</a>

views/dialog/partial/last.php
<?php
/* @var $this \yii\web\View */
/* @var $models \app\modules\communication\models\Dialog[] */

use yii\helpers\Url;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use app\modules\user\widgets\UserImg;
?>
<? if (!empty($models)): ?>
	<div class="list-group lg-alt">
		<? foreach ($models as $model): ?>
			<a href="<?= Url::to(['index', 'id' => $model->id]); ?>" class="list-group-item media">
				<div class="pull-left">
					<?=
					UserImg::widget([
						'model' => $model->users[0],
						'imageOptions' => ['class' => 'a-lg']
					]);
					?>
				</div>

				<? if ($model->new_message_count > 0): ?>
					<div class="pull-right">
						<span class="label label-primary m-t-20 d-ib"><?= $model->new_message_count; ?></span>
					</div>
				<? endif; ?>
				<div class="media-body">
					<div class="lgi-heading m-b-0"><?= implode(', ', ArrayHelper::getColumn($model->users, 'profile.name')); ?></div>
					<div class="lgi-text m-b-0">
						<? if ($model->lastMessage->user_id == Yii::$app->user->id): ?>
							<b><?php echo Yii::t('app/communication', 'views.dialog.partial.last.text-1') ?></b>
						<? endif; ?>
						<?= $model->lastMessage->text; ?>
					</div>
					<div class="f-10 text palette-Grey-400"><?= Yii::$app->formatter->asRelativeTime($model->lastMessage->created_at); ?></div>
				</div>
			</a>
		<? endforeach; ?>
	</div>
<? else: ?>
	<div class="p-20 text-center">
		<i class="zmdi zmdi-info-outline zmdi-hc-5x"></i><br/>
		<?php echo Yii::t('app/communication', 'views.dialog.partial.last.text-2') ?>
	</div>
<? endif; ?>

views/dialog/partial/view.php
<?php
/* @var $this \yii\web\View */
/* @var $dialog \app\modules\communication\models\Dialog */
/* @var $dataProvider \yii\data\ActiveDataProvider */

use app\modules\user\widgets\UserImg;

/* @var $model \app\modules\communication\models\Message */
?>
<? foreach ($dataProvider->models as $model): ?>
	<div class="list-group-item comm-message-list-item media<?= $model->isMy ? ' text-right' : ''; ?>" data-key="<?= $model->id; ?>">
		<div class="text-center <?= $model->isMy ? 'pull-right' : 'pull-left'; ?>">
			<?= UserImg::widget(['model' => $model->user, 'link' => true]); ?>
			<div class="ac-check">
				<input type="checkbox" class="comm-message-list-item-input acc-check" value="<?= $model->id; ?>"/>
				<span class="acc-helper"></span>
			</div>
		</div>
		<div class="media-body">
			<div class="msb-item c-pointer bg <?= $model->isMy ? 'palette-Blue-400 c-white' : 'palette-Grey-200'; ?>">
				<?= $model->getText(); ?>
			</div>
			<small class="ms-date"><i class="zmdi zmdi-time"></i> <?= Yii::$app->formatter->asDatetime($model->created_at); ?></small>
		</div>
	</div>
<? endforeach; ?>